config/routes.rb
Rails.application.routes.draw do
  get 'reviews/new'
  get 'reviews/create'
  root to: "cocktails#index"
  resources :cocktails do
    resources :doses, only: [:new, :create]
    resources :reviews, only: [:new, :create]
  end
  resources :doses, only: :destroy
  resources :reviews, only: :destroy
end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_one_attached :photo
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  has_many :reviews
  validates :name, uniqueness: true, presence: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, :cocktail, :ingredient,presence: true
  validates :cocktail, :uniqueness => { :scope => :ingredient }
end


# A dose must have a description, a cocktail and an ingredient, and [cocktail, ingredient] pairings should be unique

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, uniqueness: true, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :cocktail
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @dose = Dose.new
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :doses, :ingredients, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    # we need `restaurant_id` to associate dose with corresponding restaurant
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render "cocktails/show"
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy

    redirect_to cocktails_path
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @review = Review.new
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @review = Review.new(review_params)
    @review.cocktail = @cocktail
    @review.save
    redirect_to cocktail_path(@cocktail)
  end

  private

  def review_params
    params.require(:review).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/cocktails/_form.html.erb
<%= simple_form_for(cocktail) do |f| %>
<%= f.input :name %>
<%= f.input :photo, as: :file %>
<%= f.submit "add cocktail", class: "btn btn-primary" %>
<% end %>

app/views/cocktails/index.html.erb
<%= render "shared/banner" %>
<h1>Cocktails list</h1>

<div class="container">
  <div class="row">
      <% @cocktails.each do |cocktail| %>
        <div class="col-md-4">
          <%= link_to cocktail_path(cocktail), class: "card-link" do %>
          <div class="card-category" style="width: 18rem;">
            <%= cocktail.name %>
          </div>
          <% end %>
        </div>
      <% end %>
  </div>
</div>

app/views/cocktails/new.html.erb
<h1>Create new cocktail</h1>

<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <%= render 'form', cocktail: @cocktail %>
    </div>
  </div>
</div>

app/views/cocktails/show.html.erb
<div class="container">
  <h1><%= @cocktail.name %></h1>
  <div class="row">
      <div class="col-md-6">
        <h2>Add dose:</h2>
        <%= render 'doses/new', cocktail: @cocktail, dose: @dose %>
      </div>
      <div class="col-md-4 offset-md-1">
        <% if @cocktail.photo.attached? %>
          <%= cl_image_tag @cocktail.photo, height: 300, width: 400, crop: :fill %>
        <% else %>
            <p>"No picture"</p>
        <% end %>
      </div>
  </div>
  <br>
  <div class="row">
    <div class="col-md-6">
      <h2>Ingredients and doses:</h2>
      <ul>
        <% @cocktail.doses.each do |dose| %>
          <li><%= dose.ingredient.name %>: <%= dose.description %></li>
        <% end %>
      </ul>
    </div>
    <div class= "col-md-4 offset-md-1">
      <%= link_to "Add review", new_cocktail_review_path(@cocktail), class: "btn btn-primary" %>
      <h2>Reviews:</h2>
      <ul>
        <% @cocktail.reviews.each do |review| %>
          <li><%= review.content %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/doses/_new.html.erb
<%= simple_form_for [cocktail, dose] do |f| %>
  <%= f.input :description %>
  <%= f.association :ingredient %>
  <%= f.button :submit, class: "btn btn-primary"%>
<% end %>

app/views/doses/new.html.erb
<h1>Doses#new</h1>
<p>Find me in app/views/doses/new.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/new.html.erb
<h1>Add review</h1>

<%= simple_form_for [@cocktail, @review] do |f| %>
  <%= f.input :content %>
  <%= f.button :submit, class: "btn btn-primary"%>
<% end %>

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://source.unsplash.com/dmkmrNptMpw);">
  <div class="container">
    <h1>Your <strong>best cocktails</strong> brought <strong>to you</strong>!</h1>
    <p>Check the best cocktails or create your own.</p>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-light bg-light justify-content-between">
  <%= link_to "", cocktails_path, class: "fas fa-cocktail" %>
  <form class="form-inline">
    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
    <%= link_to "Add cocktail", new_cocktail_path(@cocktail), class: "btn btn-outline-success my-2 my-sm-0" %>
  </form>
</nav>